name: CI Testing
on: [push, pull_request]
jobs:
  testing:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#skip-build') }}
    steps:
      - uses: actions/checkout@v3

      - name: Login to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Initialize submodules
        run: |
          git submodule init
          git submodule update

      - name: Prepare container
        run: |
          docker pull ghcr.io/netivism/docker-neticrm-ci:drone-php7
          git clone -b drone-php7 https://github.com/NETivism/docker-neticrm-ci.git
          docker run -d --name neticrm-ci-php7 -p 8080:8080 -v $GITHUB_WORKSPACE:/mnt/neticrm-7/civicrm -e "TZ=Asia/Taipei" -e "RUNPORT=8080" -e "DRUPAL_ROOT=/var/www/html" -e "CIVICRM_TEST_DSN=mysql://root@localhost/neticrmci" ghcr.io/netivism/docker-neticrm-ci:drone-php7

      - name: Install netiCRM
        run: |
          docker exec neticrm-ci-php7 /init.sh
          docker exec neticrm-ci-php7 bash -c "cd /var/www/html && drush status | grep version"
          docker exec neticrm-ci-php7 bash -c "php -v"

      - name: Unit Test - Type test
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/phpunit && phpunit CRM/Utils/TypeTest.php"
      - name: Unit Test - Contribution - Duplicate receipt id test
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/phpunit && phpunit --filter testLastReceiptId CRM/Contribute/BAO/ContributionTest.php"
      - name: Payment Test - ALLPAY
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/phpunit && phpunit CRM/Core/Payment/ALLPAYTest.php"
      - name: Payment Test - Neweb(new)
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/phpunit && phpunit CRM/Core/Payment/SPGATEWAYTest.php"
      - name: Payment Test - LINE Pay
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/phpunit && phpunit CRM/Core/Payment/LinePayTest.php"
      - name: Payment Test - TapPay
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/phpunit && phpunit CRM/Core/Payment/TapPayTest.php"
      - name: Payment Test - Backer 
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/phpunit && phpunit CRM/Core/Payment/BackerTest.php"
      - name: API Test - Contribution Recur
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/phpunit && phpunit api/v3/ContributionRecurTest.php"
      - name: API Test - Get Options
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/phpunit && phpunit api/v3/GetOptionsTest.php"
      - name: API Test - Phone
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/phpunit && phpunit --group CItesting api/v3/PhoneTest.php"
      - name: API Test - Participant
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/phpunit && phpunit --group CItesting api/v3/ParticipantTest.php"
      - name: API Test - Activity
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT/sites/all/modules/civicrm/tests/phpunit && phpunit --group CItesting api/v3/ActivityTest.php"
      - name: Frontend - All Pages
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT && casperjs test sites/all/modules/civicrm/tests/casperjs/pages.js"
      - name: Frontend - Event Registeration
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT && casperjs test sites/all/modules/civicrm/tests/casperjs/event_register.js"
      - name: Frontend - Import Records
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT && casperjs test sites/all/modules/civicrm/tests/casperjs/import.js"
      - name: Frontend - Add Contact
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT && casperjs test sites/all/modules/civicrm/tests/casperjs/add_contact.test.js"
      - name: Frontend - Edit Contact
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT && casperjs test sites/all/modules/civicrm/tests/casperjs/edit_contact.test.js"
      - name: Frontend - Search Tasks
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT && casperjs test sites/all/modules/civicrm/tests/casperjs/batch_action.test.js"
      - name: Frontend - Event Editing
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT && casperjs test sites/all/modules/civicrm/tests/casperjs/add_event.test.js"
      - name: Frontend - Participant Editing
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT && casperjs test sites/all/modules/civicrm/tests/casperjs/event_participant.test.js"
      - name: Frontend - Contribution Page Editing
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT && casperjs test sites/all/modules/civicrm/tests/casperjs/add_contribution_page.test.js"
      - name: Frontend - Contribution Editing
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT && casperjs test sites/all/modules/civicrm/tests/casperjs/new_contribution.test.js"
      - name: Frontend - Custom Data
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT && casperjs test sites/all/modules/civicrm/tests/casperjs/custom_data.test.js"
      - name: Frontend - Group Editing
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT && casperjs test sites/all/modules/civicrm/tests/casperjs/add_group.test.js"
      - name: Frontend - Advanced Search
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT && casperjs test sites/all/modules/civicrm/tests/casperjs/advanced_search.test.js"
      - name: Frontend - Profile Editing
        run: docker exec neticrm-ci-php7 bash -c "cd \$DRUPAL_ROOT && casperjs test sites/all/modules/civicrm/tests/casperjs/add_profile.test.js"
  notification:
    if: ${{ failure() }}
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Shorten sha
        id: vars
        shell: bash
        run: echo "::set-output name=sha_short::${GITHUB_SHA::7}"

      - name: Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{secrets.NETIVISM_EMAIL_HOST}}
          server_port: ${{secrets.NETIVISM_EMAIL_PORT}}
          username: ${{secrets.NETIVISM_EMAIL_LOGIN}}
          password: ${{secrets.NETIVISM_EMAIL_PASSWD}}
          to: ${{secrets.NETIVISM_NOTIFICATION_TARGET}}
          from: Github Workflow
          secure: false
          ignore_cert: true
          convert_markdown: true
          subject: "[${{github.repository}}] Run failed: ${{github.workflow}} - ${{github.ref_name}} (${{steps.vars.outputs.sha_short}})"
          body: |
            Executed by: ${{github.actor}}
            Job name: ${{github.job}}
            Repository: ${{github.repository}}
            Status: ${{job.status}}
            SHA: ${{github.sha}}
            Message: ${{ github.event.head_commit.message }}
            Link: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
